name: Label Commits Based on Message

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add labels based on commit message
        uses: actions/github-script@v6
        with:
          script: |
            const labels = [];
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            commits.data.forEach(commit => {
              const message = commit.commit.message;

              if (message.startsWith('feat:')) {
                labels.push('feature');
              } else if (message.startsWith('fix:')) {
                labels.push('bug');
              } else if (message.startsWith('docs:')) {
                labels.push('documentation');
              } else if (message.startsWith('style:')) {
                labels.push('style');
              } else if (message.startsWith('refactor:')) {
                labels.push('refactor');
              } else if (message.startsWith('perf:')) {
                labels.push('performance');
              } else if (message.startsWith('test:')) {
                labels.push('test');
              } else if (message.startsWith('chore:')) {
                labels.push('chore');
              }
            });

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels,
              });
            }
